[package]
name = "arysn"
version = "0.1.0"
authors = ["Tahara Yoshinori <read.eval.print@gmail.com>"]
edition = "2018"
license = "MIT"
description = "ORM code generator"

[dependencies]
Inflector = "0.11"
anyhow = "1"
chrono = "0.4"
deadpool = "0.5"
deadpool-postgres = "0.5"
dyn-clone = "1"
env_logger = "0.7"
log = "0.4"
proc-macro2 = "1"
quote = "1"
syn = "1"
thiserror = "1.0"
tokio = { version = "0.2", features = ["full"] }
tokio-postgres = { version = "0.5", features = ["with-chrono-0_4"] }
