[package]
name = "arysn"
version = "0.1.0"
authors = ["Tahara Yoshinori <read.eval.print@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = "0.11"
anyhow = "*"
chrono = "0.4"
env_logger = "*"
log = "*"
proc-macro2 = "*"
quote = "1"
syn = "1"
tokio = { version = "0.2", features = ["full"] }
tokio-postgres = { version = "0.5", features = ["with-chrono-0_4"] }
